// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN19HjdcGM81SYrBj0ajn1xvho1oSpcgo',
    appId: '1:709509671562:web:d6745dd9e1f401dbac9b73',
    messagingSenderId: '709509671562',
    projectId: 'notifiacionoptionhelp',
    authDomain: 'notifiacionoptionhelp.firebaseapp.com',
    storageBucket: 'notifiacionoptionhelp.firebasestorage.app',
    measurementId: 'G-2X9BGB7JZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFMOl4Z7sbln3HbpjloEDtjRGidGtk-MI',
    appId: '1:709509671562:android:3c1531b51c072a4dac9b73',
    messagingSenderId: '709509671562',
    projectId: 'notifiacionoptionhelp',
    storageBucket: 'notifiacionoptionhelp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1B9XydnjDUiJEVrLhU2WEPVRNsjAk1YY',
    appId: '1:709509671562:ios:125cde2c8535af74ac9b73',
    messagingSenderId: '709509671562',
    projectId: 'notifiacionoptionhelp',
    storageBucket: 'notifiacionoptionhelp.firebasestorage.app',
    iosBundleId: 'com.example.optionHelp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1B9XydnjDUiJEVrLhU2WEPVRNsjAk1YY',
    appId: '1:709509671562:ios:125cde2c8535af74ac9b73',
    messagingSenderId: '709509671562',
    projectId: 'notifiacionoptionhelp',
    storageBucket: 'notifiacionoptionhelp.firebasestorage.app',
    iosBundleId: 'com.example.optionHelp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN19HjdcGM81SYrBj0ajn1xvho1oSpcgo',
    appId: '1:709509671562:web:31a40a6db43df01dac9b73',
    messagingSenderId: '709509671562',
    projectId: 'notifiacionoptionhelp',
    authDomain: 'notifiacionoptionhelp.firebaseapp.com',
    storageBucket: 'notifiacionoptionhelp.firebasestorage.app',
    measurementId: 'G-VVXK72L8PT',
  );
}
